Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Mvc;
using _20221118_NeptunoMVC.Models;

namespace _20221118_NeptunoMVC.Controllers
{
    public class CategoriesController : Controller
    {
        public IActionResult Index()
        {
            CategoriesModel cm = new CategoriesModel();
            var lista = cm.GetCategories();

            ViewData["categories"] = lista;

            return View();
        }
    }
}

Controllers/StatsController.cs
using _20221118_NeptunoMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace _20221118_NeptunoMVC.Controllers
{
    public class StatsController : Controller
    {
        public IActionResult Top5()
        {
            StatModel sm = new StatModel();
            var top5 = sm.GetTop5();

            ViewData["Empleados"] = "[";
            ViewData["Amounts"] = "[";

            foreach (var item in top5)
            {
                ViewData["Empleados"] += "'" + item.EmployeeName + "', ";
                ViewData["Amounts"] += ((decimal)item.Amount).ToString("N2").Replace(".","").Replace(",", ".") + ", ";
            }
            ViewData["Empleados"] = ViewData["Empleados"].ToString().Remove(ViewData["Empleados"].ToString().Length - 2);
            ViewData["Amounts"] = ViewData["Amounts"].ToString().Remove(ViewData["Amounts"].ToString().Length - 2);
            ViewData["Empleados"] += "]";
            ViewData["Amounts"] += "]";

            //Preparacion de viewdata
            //['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange']  - empleados
            //[12, 19, 3, 5, 2, 3] - importes

            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Neptuno ERP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/css/lightbox.min.css" integrity="sha512-ZKX+BvQihRJPA8CROKBhDNvoc2aDMOdAlcm7TUQY+35XYtrd3yh95QOOhsPDQY9QnKE0Wqag9y38OIgEvb88cA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/Images//nw logo.jpg" height="90" alt="Northwind logo"  title="Northwind logo" />
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categorias</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Productos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Stats" asp-action="Top5">Top 5</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    
    <main role="main" class="pb-3">
        <div class="container">
            @RenderBody()
        </div>
    </main>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Neptuno ERP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/js/lightbox.min.js" integrity="sha512-k2GFCTbp9rQU412BStrcD/rlwv1PYec9SNrkbQlo6RZCf75l6KcC3UwDY8H5n5hl4v77IDtIPwOk9Dqjs/mMBQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>